name: UpdateToken

on:
  schedule:
    - cron: '*/10 * * * *'

inputs:
  branch:
    description: The name of the branch to use for the script execution and push changes
    default: raw_transactions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ inputs.branch }}

    - name: Run script
      run: |
        pip install defichain~=2.3.0
        python3 defichain/transactions/constants/tokens.py

    - name: Commit changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Updated token at $(date +'%Y-%m-%d %H:%M:%S')"

    - name: Push changes
      uses: ad-m/github-push-action@v0.7.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
